x-aliases:
  - &pg_envs
    POSTGRES_DB: studigarage
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: no_pass

services:
 
  db:
    image: postgres
    restart: always
    environment:
      <<: *pg_envs
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata: